version: '3.8'

services:
  db:
    image: mysql:8.0.26
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_pass
      MYSQL_DATABASE: db_name
    volumes:
      - database:/var/lib/mysql

volumes:
  database: